name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    env:
      VITE_APP_BASE_URL: ${{ secrets.API_URL }}
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'no-tomatoes-tonight-or-id-scream'
        reponame: 'image-restorer-frontend'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
